apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: rahulvadisetty91/assignment:v1.0.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: database-secret
          volumeMounts:
            - mountPath: /opt/server
              name: config
      volumes:
        - configMap:
            name: config
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yml: |
    server:
      port: 5000
    db:
      host: postgres.default.svc.cluster.local
      port: 5432
      username: postgres
      password: root
      databse: template0

